version: '3'

services:
  dev:
    image: node:lts
    volumes:
      - nodemodules:/app/node_modules
      - .:/app
    working_dir: /app
    command: npm run dev
    ports:
      - 5173:5173

volumes:
  nodemodules:
    external: true
